### ISSUE TITLE
When things don't, where to go for help

### ISSUE THREAD

**Issue by stvaiello** [zenoss/zenpacklib#103]
Made my first attempt at zenpacklib to create a new device & component following tutorial examples. No errors aren't being thrown, but components never show. So would be nice to have a documentation page to cover more detailed troubleshooting / debugging / where to get help. Raising this question to my account Rep, they suggested opening an issue here.

**Comment by cluther** [comment]
@stvaiello: It may be useful for you to run through the following tutorial. It provides good ways to check your progress as you go to make sure things are setup correctly.

http://zenpacklib.zenoss.com/en/latest/tutorial-snmp-device/index.html

Specifically the following section may be appropriate to your questions. Though I'd recommend going through the tutorial from beginning to end as it builds throughout and you lost a lot of important context jumping straight to one section.

http://zenpacklib.zenoss.com/en/latest/tutorial-snmp-device/component-modeling.html#test-temperaturesensor-class

I'm not sure how far you've gotten, but the idea is that your zenpack.yaml file is only specifying the classes of components that could exist. Ultimately you must create one or more modeler plugins to create instances of those component classes.

**Comment by stvaiello** [comment]
I didn't want to g into specifics of my issue, and just leave the ticket as a general issue of, "when I follow the tutorial & things aren't working as expected....  What do I do, where do I go next to debug"

For my particular issue; I followed both the SNMP tutorial and the HTTP-API ones in succession. Since each section builds on the next (and the HTTP-API tutorial seems to assume you followed the SNMP one already). I have a Device & Component class defined in the yaml file, and a theoretically working modeler plugin. But the components never display. And following the "tutorial-snmp-device/component-modeling" for the zendmd commands to test the component class & relationship, that does not work either. So I am guessing that is where my issue is...  but documentation/tutorials do not guide how to debug from there.

**Comment by cluther** [comment]
Understood. I've added an item to zenpacklib's backlog to add troubleshooting documentation.

In the meantime you can open support cases to assist in troubleshooting specific issues as zenpacklib is supported. Alternatively you can post to the community forums or ask in #zenoss on irc.freenode.net.
