### ISSUE TITLE
Possible missing line in zenpack.yaml "Configure Monitoring Templates" section

### ISSUE THREAD

**Issue by stvaiello** [zenoss/zenpacklib#105]
I believe the zenpack.yaml is missling a line, the name of the template. Shouldn't it be:

    device_classes:
     /WeatherUnderground:
       templates:
         Location:
           description: Location weather monitoring using the Weather Underground API.
           targetPythonClass: ZenPacks.training.WeatherUnderground.WundergroundLocation

           datasources:
             alerts:
               type: Python
               plugin_classname: ZenPacks.training.WeatherUnderground.dsplugins.Alerts
               cycletime: "600"

This would also apply to the next page "datasource-plugin-datapoints"

**Comment by stvaiello** [comment]
Thought this would open the issue against the specific page. The above issue applies to the "tutorial-http-api/datasource-plugin-event" page.

**Comment by cluther** [comment]
Thanks for pointing this out. It's corrected now.
