### ISSUE TITLE
zenpacklib DEFAULTS behavior

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#109]
if i set yaml like this:

classes:

  DEFAULTS:
    properties:
      description:
        label: Description
        label_width: 200

then later if I add more properties to a component:

RegisteredComponent:
    base: [zenpacklib.HardwareComponent]
    properties:
      perfmon_id:
          label: blah

what I am seeing is that i can see the properties set in the DEFAULTS on the details panel but they dont stay on the javascript grid.  so id see perfmon_id in the grid and description only in the details panel.

I may be making a mistake in the way im using defaults to set properties, not sure ie maybe you can only really use defaults for scalar values and not lists or something for gui things.

**Comment by eedgar** [comment]
I think this is a bug if the properties arent being set in the grid and details panel both.  I don't yet understand how your situation could be happening since the defaults are merged into the spec very early in the process.

**Comment by dougsyer** [comment]
Inhereted properties work and overriding properties work.  I changed it to not use Defaults for the properties container for now.

When i set defaults on class i think it happens on subclasses if i give them their own properties:

I assumed either that would totally override the child classes properties or would add to them..

**Comment by dougsyer** [comment]
I saw the issues with trying to inherit relations too but looks like yiu guys fixed it..

**Comment by eedgar** [comment]
Doug,
Are you saying this issue is resolved now and can be closed?

Eric

**Comment by dougsyer** [comment]
im going to give it a shot tonight, ill close it if it looks good.

**Comment by dougsyer** [comment]
okay looks like now if I do this it works.  i see the property on every class and also I can see it on the grid and the details display..  thanks guys.

classes:

DEFAULTS:
    properties:
      testfield:
        label: Description
