### ISSUE TITLE
list schema support

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#110]
i have a couple of zenpacks that use lists.  I'm ot sure if I should be using text lines or something..

i noticed there is no list schema support?

schema_map = {
            'boolean': schema.Bool,
            'int': schema.Int,
            'float': schema.Float,
            'lines': schema.Text,
            'string': schema.TextLine,
            'password': schema.Password,
            'entity': schema.Entity
            }

**Comment by cluther** [comment]
`lines` should be used for lists. A list is the internal representation. The input format is a text area that will be converted into one list element per line.

**Comment by dougsyer** [comment]
okay thanks.
