### ISSUE TITLE
boolean grid display + renderer + editable = True

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#111]
Im trying to set a boolean value to render as a checkbox in the grid but also have it editable.  This worked for me in the old style zenpack development but i cant get it to work with zplib.
by default it looks like the boolean renders as true/false in the grid so I just added a renderer (see below) ..the build in one.

when I do that the javascript grid renders as a checkbox but i cant edit it in the details panel.  in fact, the label for the field dissapears but i can see the checkbox.

unreg_alert:
        label: UnReg Alert
        type: boolean
        default: false
        editable: true
        grid_display: true
        renderer: Zenoss.render.checkbox

old style id just do this and I could edit the property and see it in the grid.

object.py:
 {'id': 'tunnel_monitor', 'type': 'boolean'},
in the api:
tunnel_monitor = schema.Bool(title=_t(u'Monitor for tunnel down alerts'), alwaysEditable=True)
in the javascript: 
id: 'tunnel_monitor',
                dataIndex: 'tunnel_monitor',
                header: _t('Alert'),
                width: 60,
                renderer: Zenoss.render.checkbox,
                sortable: true,

![checkbox1](https://cloud.githubusercontent.com/assets/1815352/9208267/8e79609e-4040-11e5-9015-de6378d9fedc.JPG)
![checkbox2](https://cloud.githubusercontent.com/assets/1815352/9208277/a4478072-4040-11e5-8369-5a1af8195bed.JPG)

**Comment by dougsyer** [comment]
actually i just checked on a non boolean field with editable = true and it seems to be doing something similar except i cant see the field at all in the details panel.

I know it exists, i can see it in the grid and I can see it in ZMI/DMD.  just not rendering in the details panel and the save button is greyed out(im logged in as admin).  im wondering now if there isnt an issue with the class security and the rendering but i'll play with it some more.

high_calls_threshold:
        label: High Calls Threshold
        type: integer
        default: -1
        editable: true

**Comment by dougsyer** [comment]
i will also create a support case on this one as it is blocking a project im working on.

**Comment by eedgar** [comment]
doug I will take a look to see if I can figure out whats going on.  Its been a little while since I messed with the editable parameters.

**Comment by dougsyer** [comment]
Thanks.  Always a chance its just something i did but i have a feeling thst maybe before the details panel didnt share the same renderes/forms like they do with zplib bur thats not much more than a hunch

**Comment by eedgar** [comment]
can you try True instead of true?

**Comment by dougsyer** [comment]
turns out one problem i had was i made my integer type as type: integer and not type:int, that caused the property to still be there but is was a string.  the second issue is that it looks like the boolean value is true in the grid instead of  a checkbox and if i used the read-only checkbox renderer it messes up the details page.  but the issues as initially reported is not accurate.  the editable fields work its just the boolean rendering is a bit funky.

**Comment by dougsyer** [comment]
i just tested the latest hotfix, it is fixed for me.
