### ISSUE TITLE
problems setting M-M relations

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#113]
I have a ZP where im setting M:M relations.

What Ive found is if you have relations like this:

MyCustomDevice 1:M Component1
MyCustomDevice 1:M Component2
Component1 M:M Component2

and you have duplicate ids between components, you can have a situation where the search in the returns the incorrect component so you get a traceback like this:

ZenSchemaError: ('component1 restricted to class Component1. Default is class Component2', None)

In this case I have a component with an id named "Default" in two different classes.  that seems be causing the issue, there is no constraint with the device types im working with to have a unique id name for every component and often you will fine multiple components named "Default" along with other duplicate component names..

I know i can modify the ids with a tag to make them unique but that causes a variety of problems in my polling datasources/plugins.

it appears that in zenpacklib.py, this search will only return one matching id? I tried the same query against the built in componentBase and got the same result, only one object...only in componentBAse I could also specify a meta type..

 def setIdsInRelationship(self, relationship, ids):
        """Update ToMany relationship given relationship and ids."""
        new_ids = set(ids)
        current_ids = set(o.id for o in relationship.objectValuesGen())
        changed_ids = new_ids.symmetric_difference(current_ids)

        query = Or(*[Eq('id', x) for x in changed_ids])

        obj_map = {}
        for result in self.device().search('ComponentBase', query):
            obj_map[result.id] = result.getObject()

**Comment by dougsyer** [comment]
looks like in the previous version of the updateToMany (from the older tool kits) had a type that was passed and it searched the componentSearch Catalog so this issue didnt happen before.  I used this on other zenpacks before zenpacklib:

def updateToMany(relationship, root, type_, ids, log):
    '''
    Update ToMany relationship given search root, type and ids.

    This is a general-purpose function for efficiently building
    non-containing ToMany relationships.
    '''
    root = root.primaryAq()

    new_ids = set(map(prepId, ids))

    current_ids = set(o.id for o in relationship.objectValuesGen())
    changed_ids = new_ids.symmetric_difference(current_ids)

    query = Or(*(Eq('id', x) for x in changed_ids))

    obj_map = {}
    for result in ICatalogTool(root).search(types=[type_], query=query):
        obj_map[result.id] = result.getObject()

    for id_ in new_ids.symmetric_difference(current_ids):
        obj = obj_map.get(id_)
        if not obj:
            continue

        if id_ in new_ids:
            relationship.addRelation(obj)
        else:
            relationship.removeRelation(obj)

        # Index remote object. It might have a custom path reporter.
        notify(IndexingEvent(obj, 'path', False))

        # For componentSearch. Would be nice if we could target
        #idxs=['getAllPaths'], but there's a chance that it won't exist
        # yet.
        obj.index_object()

**Comment by dougsyer** [comment]
Im wondering now if this will indirectly cause problems with unindexing components after they are deleted..if you have duplicate ids across components?

**Comment by cluther** [comment]
Zenoss and zenpacklib make assumptions in many places that component IDs are unique within a device. I'd highly encourage you to make this the case. The most common problem you'll find if you have two components with the same ID is when an event arrives with its evt.component field set to that duplicate ID. Zenoss will attribute the event to one of the components in a non-deterministic way.

**Comment by dougsyer** [comment]
I hear you with the events, i have plugins to deal with some of it but yeah it will probably land in a random place.   I though at one point that there was a a way to force an event to either a title or an id?  now that im thinking about it, im not sure that ever worked...maybe it did work before the catalog stuff, now im assuming that there is a catalog lookup to get the link and the component goes to one returned at the top of the list?

I added a mixin that handles the toMany relations correctly and that models correctly but now that you have confirmed that zenpacklib assumes component id uniqueness (maybe I read that somewhere and forgot)...it is probalby the case that the componentbase catalog will be a mess as well if I dont make unique ids across classes.. 

Actually I think this may work out because im using title in most cases to get data form the various polling plugins it just stinks to have to add duplicated metadata to each component.  ie the class defines uniqueness as does the relation and now I have to add a text tag to the ID that essentially duplicates the class/meta_type info.
