### ISSUE TITLE
removal method for non containing relations 

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#119]
I believe if you pass None to set_{relationshipname} it will never actually remove a relation, it just changes it.

I have a situation where i need track when relation are no longer there.  i will make a custom method for now but im assuming there are cases out there where you may want to remove a relation rather than change it.

doug

**Comment by dougsyer** [comment]
i have to test this more but im trying to remove a 1-M relationship from the class on the "to one" side. Of the relationship.  I think i can probably just store up the changes and remove them via the "to many side". That is probaly more efficient anyways.  Im doing this with a pyth. Collector poll but ive never had the need to remove and not just move a 1-m rel.

**Comment by eedgar** [comment]
Doug,
Chet recently mentioned this defect in an internal discussion.  We are aware of the issue and need to fix it.  I have pushed to have it fixed for 1.0.4 but we will see what happens.
Eric

**Comment by dougsyer** [comment]
thanks Eric.  i'll probalby just set it from the to many side, havent done that yet but im not sure in terms of performance what is better...probalby depends on the nature of what im trying to do.

**Comment by dougsyer** [comment]
i think this if fixed now..
