### ISSUE TITLE
eventclass/eventclass instance

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#127]
I saw eric had a branch that added event class/event class instance support.  that would be handy since im always forgetting to export the zp etc every time i add one of these..

not sure if you guys are going to add this to the main branch?

**Comment by cluther** [comment]
We are planning on adding it. We just need to consolidate some organizer handling code so that generic organizer things work the same way under /Events as they'd work under /Devices.

**Comment by dougsyer** [comment]
Sweet thanks.  I suffer from forget to export syndome..

**Comment by dougsyer** [comment]
tks

**Comment by rvykunta** [comment]
Doug,  Can you check on your pending ZPL requests and let us know if there is anything major that's remaining that needs to be considered for v2.0.0; I also sent you an email on the upcoming release of ZPL v2.0.0 and it's content.. Can you check it out and let us know your feedback? 
Regards,
-Rama.
