### ISSUE TITLE
zenpacklib does not work in zenoss 5

### ISSUE THREAD

**Issue by JayCeeJr** [zenoss/zenpacklib#128]
There appears to be an issue with relationships using Zenoss 5.0.6

I exported the working wunderground example zenpack from 4.2.5 and recieve the following error from zenoss 5

2015-10-20 21:58:42,881 INFO zen.ZenHub: Worker (5385) reports 2015-10-20 21:58:42,880 WARNING zen.ApplyDataMap: no relationship:wundergroundLocations found on:wunderground.com (<class 'Products.ZenModel.Device.Device'> )

https://github.com/JayCeeJr/zenpack.training.wunderground

**Comment by cluther** [comment]
That "no relationship:wundergroundLocations" warning usually indicates either that zenhub hasn't been restarted since the code was installed. Alternatively you could also see it if zenhub has been restarted, but the device was created after adding the code, but prior to adding the device.
