### ISSUE TITLE
datasource inheritance Calculated Datasource with Defaults

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#129]
I'm having an issue where when i implement yaml like you see below, everything sets correctly except the following fields:

targetmethod is set to getElement
targetDataSource is set to ''

other DEFAULTS in templates seem to be working okay at least for graphs i can set the default graph widths to 1000 across all graphs in a datasource.  but that obviously isn't the template spec...
I've deleted the templates completely to make sure it wasn't just some old template i was picking up...

I have alot of calculated data sources and the yaml gets very repetitive with the aggregating data source in the yaml especially as im rolling up multiple levels of stats.
here is what im doing, generically..

datasources:
          DEFAULTS:
            type: Datapoint Aggregator
            targetMethod: someComponentRelation
            targetDataSource: my_datasource
          DS1:
            targetDataPoint: MyDataPoint
            datapoints:
              MyDataPoint:
                operation: sum
          DS2:
            targetDataPoint: MyDataPoint2
            datapoints:
              MyDataPoint2:
                operation: sum
.

**Comment by dougsyer** [comment]
okay yeah it looks like this isnt so much a zenpacklib issue as an issue with how those classes are instantiated.

you cant it seems set defaults other than the datasource type for zenproperty monitor...calculated datasource.  may not seem like a big deal but im working with a BIG yaml..

**Comment by cluther** [comment]
@dougsyer: I haven't tested this myself yet. Can you clarify the problem here? It sounds like you're saying that DEFAULTS under datasources only allows adding defaults for the fields in the most basic datasource type, and that extended datasource type properties like targetMethod in Datapoint Aggregator don't honor property values set in DEFAULTS.

**Comment by dougsyer** [comment]
Yes, I think that is the issue, i didnt understand why some fields worked but I think you are probably correct in that its the non default properties that have the issue.  IDK if its zenpacklib or he way those class/instance attributes are set or initialized.

**Comment by cluther** [comment]
That seems like a bug to me. I'll leave the _bug_ label on this issue and assume that's the case until someone can test it.

**Comment by dougsyer** [comment]
this is working now with the latest update.
