### ISSUE TITLE
feature request ability to cut zenpack into multiple yamls..

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#160]
Im not sure if there is a way to do this in a supported way.  i love the yaml format but templates can make it huge..

**Comment by cluther** [comment]
There's no way to do this currently.

**Comment by dougsyer** [comment]
yeah i figured.  its kind of a first world problem but id like to cut the template yamls into smaller files that are easier to work with but its not a huge issue.

**Comment by rvykunta** [comment]
Doug, 
This is available now in v2.0.0 and you can check it out. Can you check on your pending ZPL requests and let us know if there is anything major that's remaining that needs to be considered for v2.0.0; I also sent you an email on the upcoming release of ZPL v2.0.0 and it's content.. Can you check it out and let us know your feedback?
Regards,
-Rama.

**Comment by dougsyer** [comment]
awesome thanks.  i'll close this one for now.
