### ISSUE TITLE
Negative integers (min graph fields)

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#175]
I'm not sure if i covered this issue exactly but it has to do I think with some of the field type issues ive seen.

if i set miny / maxy to a negative number, i think that it is being interpreted as a string and not a number.  So the negative min value doesnt set.  so in the yaml try to set miny to say -100..

i tried doing !!int etc yaml shortcuts but i suspect that when you set it as negative that the value gets set as  a string.  when its positive it gets set as an int.

**Comment by dougsyer** [comment]
im talking about the graphdef settings not the rrd constraints.  i havent tried setting the rrd constraints using the zenpacklib yet.

**Comment by j053ph4** [comment]
Hi Doug,

This might be a platform issue (at least on 4.2.5 where I'm looking) -- it looks to me like the negative value is set correctly (and of the right type), but is getting ignored (even if set manually in the template).

**Comment by dougsyer** [comment]
hey i think that its actually working now...not sure why...maybe one of the updates or something idk.

**Comment by dougsyer** [comment]
Some of my confusion at leadt with zen 4 is that it appears if you set the mom and maxy y attributes in the gui that once you chsmge the auto scalling setting of -1 to a graph you can never turn the auo scaling back on.  If you set it back to -1 it uses litteral -1
