### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#45]
Some things ive spent alot of time when working on zenpacks.  At risk of embarrassing myself here.

how to call the methods updating non containing relationships in a modeller:

- not alot of helpful errors sometimes when you are feeling this out when writing a modeler so for me at least if would of helped to know exactly what parameters you need to call these.  
- for example, I think the methods are named differently named now but I got stuck a couple of times with having to pass in the full class ie mycomponent.mycomponent.ZenPacks.. 
- how to efficiently get the lists you need to update the relationships on m-1 ...i think this is taken care of now with the new lib so you dont need to worry about it as much

path reporters

I got them running several different ways now but it was trial and error and I was a bit worried about the efficiency of the code.  Some of the styles ie putting them with the object, adding them as a separate file, threw me off some.  The logic could use some explaining...its probably baked in now mostly.  Some basic troubleshooting documentation would help, ie I learned to check in the browser and the catalog to figure out what Ive done wrong.

the api for dynamic view.

- i had to do it with zenstorage base which made it harder since there was some override trickery involved.  I gave up after a while since I wanted to try it fresh on another zenpack.

**Comment by cluther** [comment]
Agreed on all the suggested documentation updates.

As of the first release (1.0.0) of zenpacklib, version information is included.

**Comment by dougsyer** [comment]
Tks
