### ISSUE TITLE
register with zencatalogscan?

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#46]
I hate to leave a circular issue request here but we have come to really rely on the zenoss toolkit.  It would be great if there was some way to register your custom indexes so that they can be automatically picked up by zencatalogscan..

Most of the ZenPacks with catalog customization re pretty critical and usually some of the most complex to support(ie the vendors monitoring apis have alot of bugs and its hard to get to root cause ina  timely fashion).  I dont think i can long term keep up with manual requests to check indexes.

Please see this ticket for a discussion regarding updating the toolbox for new checks.

https://github.com/zenoss/zenoss.toolbox/issues/35

**Comment by cluther** [comment]
This will probably end up being an enhancement to the toolkit, not zenpacklib.

**Comment by dougsyer** [comment]
Yeah i can manually repoint the toolkit if i need to
