### ISSUE TITLE
Feature request yaml export?

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#50]
I find particularly right after development when a hit a bunch of real world devices i end up modifying templates in my production instance because it can reach all the various devices i need to get to  I then end up manually mosidying the templates in my dev instance...then need to reinstall preproduction.

We rarely install zenpacks on the production side in dev mode due to the high risk of having development artifacts in the zenpack.

I see here i can do the templates originally in YAML and that is great..but in practice i need to be able to go in the opposite direction ie templates ->yaml.  Even in development its easier to make mass changes in yaml but tweak colors, groupings, etc in the gui.

Keeping the yaml in sync at the same time helps when say i want to have a consistent label for the same stat across different components.  

What i mean is that i often realize at thr end of development that  i have a stat like packets per second labeled as "packet throughput" for one compoment and labeled "throughput" on another component or i have the unit inconsistencied like PPS in one graph and packets/second on another.  Those changes Are easier made via yaml but id like to get the most recent version of the templates out of dmd first.

It also would help when Im having someone QA before we go production because its easier to spot mistakes in a serialized format.  Nothing adds to the tedium of all the template wrangling like realizing i have to change a counter to a guage after we have live rrds deployed..

I know of a few scripts to get things out and a few we have created but is rather use the toolkit.

My appologies if there is a standard way to do this now and im missing it.

**Comment by joshw** [comment]
This is now supported: http://zenpacklib.zenoss.com/en/latest/command-line-reference.html#dump-templates

**Comment by dougsyer** [comment]
Awesome thanks!
