### ISSUE TITLE
zenpacklib for UI customization

### ISSUE THREAD

**Issue by sulakshm** [zenoss/zenpacklib#56]
I created zenpacks using zenpacklib. All was well.
I moved to device UI customization and wanted to introduce new fields in the device overview panel of my device page.

I did some research and found out that
1. for= attribute on the configure.zcml is the key for adding Js scope
2. for="Products.ZenModel.Device.Device" make this global
3. for="..Ourdevice.ourdivice" limits the customization only to our device

Since we are using zenpacklib there is no explicit Ourdevice.py -> Class Ourdevice(Device).
This is part of the __init__.py file of zenpack, which zenpacklib uses for configuration building.
But If I still continue to point the device (both label match and class match) to the configuration within __init__.py
I get the following error while reinstalling zenpack.
ConfigurationExecutionError: <type 'exceptions.AttributeError'>: 'module' object has no attribute '__module__'

Now is UI customization possible while using zenpacklibs?
Is there any reference samples/docs for helping us out?
I am not sure whether the reported issue is a bug with zenpacklib or my usage.
Any help much appreciated.

**Comment by cluther** [comment]
@sulakshm: Documentation for zenpacklib has yet to be created, but I'm glad you're having a good time using it.

There is an expected way to do custom JavaScript using zenpacklib that doesn't involve any ZCML. If you want to have your JavaScript file loaded for all Zenoss pages, put it in `resources/global.js`, and if you want it to only apply to your custom device type(s), put it in `resources/device.js`. If zenpacklib detects the presence of either of these files it will wire up the ZCML stuff for you automatically.

Let me know whether or not this works for you so I can update the issue accordingly.

**Comment by sulakshm** [comment]
This resources directory should be in the same level as zenpacklib?
It is usually under browser. Please clarify.

**Comment by cluther** [comment]
@sulakshm: The resources/ directory should be in the same directory as zenpacklib.py, not under browser as you may have seen as a convention in some other ZenPacks.

**Comment by karthikarjunan** [comment]
Hi @cluther 

Thanks for the info. Now the Panel shows the fields we want. However how do we get the value for certain attributes we are interested at device class level?

I am following this zenpack example from Products.ZenModel.Device import Device
[CustomOverview](https://github.com/cluther/ZenPacks.example.CustomOverview/blob/master/ZenPacks/example/CustomOverview/__init__.py)

    from Products.ZenModel.Device import Device
    from Products.Zuul.infos import ProxyProperty
    from Products.Zuul.infos.device import DeviceInfo
    
    
    # Set a default value for a device's contact.
    Device.contact = ''
    
    # Make a device's contact available through the API.
    DeviceInfo.contact = ProxyProperty('contact')

However the example shows how to set a global device property and not for a particular deviceclass property. 
And where should I write the code. I assume the Device Class itself will be created at the end of the __init__ file on zenpacklib

Your help will be much appreciated

**Comment by sulakshm** [comment]
Figured out, zenpacklib rocks! I was able to accomplish much more than the long method in a jiffy.
