### ISSUE TITLE
zenpacklib and custom functions on component/device classes

### ISSUE THREAD

**Issue by sulakshm** [zenoss/zenpacklib#57]
I have a chained relation established between components. 
I figured out the property attribute for displaying chains are through 'schema.Entity'.
I was successfully able to create this property within components.
But I need some additional functions defined within component/device classes to make it work.
How can I do this when the zenpacklib spec is written?
If not, how else to initialize this relation successfully.

For ex. comp1 and comp2 are component defined part of spec.
comp1 and comp2 has a 'entity' property defined.
comp1 will have a link to comp2 and comp2 will have a link to comp1.
For establishing this link, there are usually functions defined to help with this purpose.
As an example, like below.
def comp1_to_comp2_item(): /* within comp1 class */
    return self._object().comp2()

def comp2_to_comp1_item(): /* within comp2 class */
    return self._object().comp1()

How to add these additional functions when components are specified as spec for zenpacklib?

https://github.com/zenoss/ZenPacks.zenoss.CloudStack
I am looking at cloudstack zenpack that you had written. I am trying to bring similar functionality to my zenpack but mine is build using zenpacklib. Can you tell me the same functionality can be got using zenpacklib too? My question precisely is how to introduce those additional functions within each devices and components that helps with building the relation, part of the spec?

**Comment by cluther** [comment]
Assuming you have a component class named *CompType1* you can extend what zenpacklib creates by adding a CompType1.py in the same directory as zenpacklib.py with the following example contents.

```python
from . import schema


class CompType1(schema.CompType1):
    def example_method():
        return "I'm an example method."
```

So you can see that you can extend the classes created by zenpacklib by extending schema.<classname>. Your class is the one that will be used.

**Comment by sulakshm** [comment]
Again, nice tip.. Was really helpful.
