### ISSUE TITLE
Bug: relationships_from_yuml bombs on blank lines

### ISSUE THREAD

**Issue by cajoz** [zenoss/zenpacklib#68]
#### Problematic Behavior:
If `relationships_from_yuml` encounters a blank line, it will log an error with message "parse error in relationships_from_yuml at [...]".

#### Expected Behavior:
Ignores blank lines and lines composed entirely of whitespace.

#### Proposed Solution:
Change regex for comments to `r'^\s*(?://.*)?$'.

**Comment by cluther** [comment]
This has been fixed in the develop branch which will become 1.0.0 within days.
