### ISSUE TITLE
catalog question

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#76]
when you set the scope of a catalog to be global should you see the catalog object at the device level and dmd.Devices level? Also, Im assuming ComponentBase is a catalog that will be there at the device level for all zplib devices?  does that ComponentBase Catalog serve a function?

**Comment by cluther** [comment]
@dougsyer: When a catalog's scope is set to global, the actual catalog object will be created on dmd.Devices. The name of the catalog will be the fully-qualified module name of the class under which the property with index_type and index_scope are set with a "Search suffix". So let's say you had a ZenPack named ZenPacks.example.CatalogTest that defined a class named Widget. The catalog would be dmd.Devices.ZenPacks_example_CatalogTest_WidgetSearch.

There's no default catalog, global- or device-scoped, created by zenpacklib. A catalog only gets created if a property has index_type set.

**Comment by dougsyer** [comment]
Okay yes thats what I though was supposed to happen.  Sorru for the non specific language.

When i replaced the hp proliant zplib with the new zplib and deleted and recreated devices i still saw catalogs at the device level as well as the wierd component base cat at the device level.  That didnt serm right to me.

**Comment by cluther** [comment]
It looks like both HPDeviceBay and HPEnclosure have globally-indexed properties. So I'd expect to see one catalog for each of those classes at dmd.Devices after at least one of those respective components had been modeled.

The catalogs will remain even if you subsequently delete the devices. Removing the ZenPack would be the only thing that would remove the catalogs.

**Comment by cluther** [comment]
My first comment on this issue was wrong. There is a default device-scoped catalog created by any ZenPack that uses zenpacklib to create a "Component" class. That's the ComponentBase catalog you see. I forgot that was created by default. It's created because the standard componentSearch catalog doesn't have an id index, and some of the relationship helper methods require an id index to more efficiently find components.

So it's normal to see a ComponentBaseSearch on any device associated with a zenpacklib ZenPack.

**Comment by dougsyer** [comment]
Okay thay makes me feel better and thats what Josh told me svoit componentbae.

The behavior im seeing is that after updating zenpacklib to development i see those globally scoped catalogs at the device and at dmd.devices.  That is the last thing i need to verify.  I tried to check the unit tests but U didnt sre anything there yet.

**Comment by cluther** [comment]
Could you elaborate on what you mean by a locally scoped attribute for the already created catalogs? I don't understand what that would be, or what it would be for.

**Comment by dougsyer** [comment]
so for example you have this:

'serialNumber': {'label': 'Serial Number',
                                 'index_type': 'field',
                                 'index_scope': 'global'},

i see in this example a catalog at dmd.Devices and other under the device.  I was wondering if this is the correct behavior?

I can see how it would be since you may then have another attributed scoped at the "device" level.  

Im not seeing a problem here really i just want to make sure there should be a catalog created at both levels for a globally scoped attribute.

**Comment by dougsyer** [comment]
Have a ticket on this with support .
