### ISSUE TITLE
relationships_from_yuml still exists

### ISSUE THREAD

**Issue by cajoz** [zenoss/zenpacklib#85]
The `relationships_from_yuml` function existed before to parse a YUML file defining relationships. YUML is not still used, so this function should be removed.

**Comment by cluther** [comment]
Good point. I'll remove it.

**Comment by joshw** [comment]
If you remove it, you will break existing zenpacks' ability to drop this file in place without updating to yaml.  That's why i kept it around..  Certainly it should be considered deprecated, but i'd consider keeping it a bit longer.

**Comment by cluther** [comment]
Good point.

**Comment by cluther** [comment]
Closing this issue. We need to preserve `zenpacklib.relationships_from_yuml()` for the foreseeable future.
