### ISSUE TITLE
Unit test for relations

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#94]
Ive looked for examples and ive seen examples for testing relations after modelling but id like have a set of tests that make sure relations are correct before i start working on modelling.  I know how to test the instantiation of a class, ideally though i instantiate the class and hook up the relations In tests before modelling.

**Comment by cluther** [comment]
@dougsyer: There's a way to test your relationships schema without instantiating any objects. It exists as part of Zenoss whether you're using zenpacklib or not. There's a command line tool called `zenchkschema` that can be run on any installed ZenPack as follows.

```
zenchkschema ZenPacks.zenoss.CiscoUCS
CRITICAL:root:Inverse def 'ports' for 'ServerIOCardPort.switch' not found on 'ZenPacks.zenoss.CiscoUCS.CommonSwitch'
CRITICAL:root:Inverse def 'ports' for 'ServerIOCardPort.chassis' not found on 'ZenPacks.zenoss.CiscoUCS.Chassis'
```

There are problems with your relationships schema if it prints any lines. If it prints nothing, at least the schema for your relationships is correct. To use this schema checking you previously had to add code like the following to your ZenPack's __init__.py.

```python
productNames = (
    'MyClassOne',
    'MyClassTwo',
    )
```

With zenpacklib, this productNames list is created for you, so just run ```zenchkschema ZenPacks.something.Something```.

**Comment by dougsyer** [comment]
Thats helpful.  

But will it check for example relationships like you set for layer 2 or calc performance where you add a relationship to a base component class or add a new relationship to device.device?  

Ie i set a say fictional relationship called wind_direction to device.device and i want to make sure ciscodevice or say a custom zenpack with its own device level python class gets the relationship.  

I assumed id have to instantiate both components and add relations to test that?

I find i often mess up relationships (less now with zenpacklib) and then find about about when im building the modeller and then i think its my modeller..

**Comment by cluther** [comment]
The truest test would be to instantiate the components as modeling would. Sometimes when dealing with ZenPacks with more complicated models I create a test utility that instantiates the whole thing. You can see an example of this in the XenServer ZenPack at the following URL.

https://github.com/zenoss/ZenPacks.zenoss.XenServer/blob/develop/ZenPacks/zenoss/XenServer/tests/utils.py#L28

**Comment by dougsyer** [comment]
thats exactly what I was looking for, i saw a couple of methods in various zps but this one is much more clear.

the zenchkschema tip is also great.  I already put that to good use and Im going to run that in my __init__ from now on to hopefully prevent wrecking my dev instances 1/2 way though development.
