### ISSUE TITLE
simple use case problem -> grid display of MC->1 entity

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#96]
I have a really simple use case that Im struggling with.  I know how to solve the problem with the old zenpack development methods but not sure what Im doing wrong with this.

I'll try to illustrate the situation:

Relations:

Device ->1-MC -> BIGCOMPONENT 1->MC ->LITTLECOMPONENT

I want to display a link to the parent object in the javascript grids for LITTLECOMPONET

so for example on the Javascript grid for LITTLE COMPONENT, I want to see this:  

event status icon -> LITTLECOMPONENT TITLE   -> LINK TO BIGCOMPONENT -> locking, monitored etc..

In my zenpack, i know the relationships are fine, they model fine, they pass schema tests, and I can see the link on LITTLECOMPONENT to BIGCOMPONENT in the details panel, 

I cant even get the columns to show up to display big component in the grid..  strangely, i dont see errors either in javascript doing an inspect which is typically what I see when I mess up something.

Ive tried several things using the API settings etc etc.  in the old world for a 1->M cont link id basically just tweak info/interface api and then use a entity link renderer to have it display in the grid...I could go on for several paragraphs with what Ive tried.. but I feel like this is probably very easy to do and Im missing someting.  again these are 1->Mc relationships so I didnt dive into custom path reporters etc.. im just trying to link to a component one relationship up.

is there a simple solution for this that I'm not seeing?  I reviewed the openstack yaml and since I dont have openstack and thats a very advanced zenpack, it hard to find an example.  Ive gone through the docs pretty extensively..

**Comment by cluther** [comment]
@dougsyer: I think I follow what you're saying, but what you're asking for seems to be the default behavior of zenpacklib. The component grid for a subcomponent will by default include a column that is a link to its parent component. The only way to disable this default behavior is to have a *relationships* override in the subcomponent class that species `grid_display: False` for the relationship.

Can you share your yaml?

**Comment by dougsyer** [comment]
now that is strange, i can share the yaml.  Knowing that is the default behavior..helps alot.. 

What is wierd is that it doesnt appear to even be trying to load a new component panel.. Im going to look more ar it tonight

**Comment by dougsyer** [comment]
I added some logging and i can see the javascript being generated and at first glance it seems fine.

I can see a javascript error I have to look again but i think its just the one you get when there is no match for your meta type..

I think that its not getting registered and i believe its because im adding components to the model and not a subclassed device with components, looking at the way things get registered i think that the js is not getting registered so that probably explains why the details are fine but the sub panels and grids are missing.

**Comment by dougsyer** [comment]
yeah the issue is that if you add components and dont add them to device.device it looks like the zcml linking doesnt happen so you dont get an api layer or javascript.  the relations all work when you add them manually into the __init__ and the class file its just that it doesnt get registered.  I think the fix is to add the relations to all device.device just i had adding relations to everythign if I dont need to but I think that may be the solution here.

**Comment by dougsyer** [comment]
im going to close this for now because I dont think the zplib supports extending other zenpacks with new components.
