### ISSUE TITLE
warnings on grid size showing up unexpectedly

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#98]
Just to be clear, I dont need help figuring out the warning message I mention below.  im opening this issue to check on the behavior of the logging in zenapacklib, not for the error itself..

we have a several zenpack development effort underway using zenpacklib.

one of the in progress zenpacks has the object model pretty much completed with relations but we haven't gone back to do the finishing touches on the grid/gui yet.

what Im seeing is that every time i go into dmd, i get this showing up in stdout.  I also see this in stdout every time i we get a traceback when we try to say restart zenhub.  This isnt causing a traceback...the traceback is due to something else I just see this message when I load a script, when i run dmd, when i make a mistake and cause a traceback when reloading zenpack on the dev system...

2015-06-05 13:11:20 WARNING zen.zenpacklib ZenPacks.NWN.CM: CMComponentBase custom columns exceed 750 pixels (1007)
....this repeats per component....

**Comment by cluther** [comment]
As you probably know, this is a best practice nag. Once that pixel limit is exceeded you usually end up having to scroll the component grid horizontally to see all of the columns and the auto-expanding name column is squeezed to the point of not being useful.

Are you saying that you'd prefer to not see the log?

**Comment by dougsyer** [comment]
I havent really thought about the warning in and of itself.  700 seems low we set all graphs to 1000 width and I think on my laptop here Im seeing 1500 pixels of usable space in the grid.  the default graph size seems very "square monitor" 80's to me but im no design expert.

i think i would want to supress those warnings unless I was looking for them, ie i run a check.

For me, im seeing them in stdout when i go into dmd and if i cause a traceback.

so if im seeing them in stdout im assuming that every time something loads up a zenscriptbase (or one of the lower libraries) its doing this check which seems like alot of overhead especially since this is a message that is more useful to zenpack developers than system admins.

its a nice feature to get a warning if you go over x pixels but id want to go looking for it (ie during a lint or check of some time) and i may decide to exceed the limit (assuming its 700 we definately will).

Also in the past ive seen things logged using the wrong logger/in the wrong place and then i end up seeing that log message in unexpected places (like zen user commands) and it causes confusion with the users and makes it harder to troubleshoot other issues.

So id imagine this time next year we will have at least 10 zenpacks using zenpacklib and if each one logs that for every component on every zenoss traceback...

**Comment by eedgar** [comment]
I think I am going to mark this issue as closed. 

However this tip might help in the future.

name: ZenPacks.zenoss.HP.Proliant
class_relationships:
   - HPChassis(hpsystemboard) 1:MC HPSystemBoard

classes:
  DEFAULTS:
    base: [ManagedHardwareObject]
  HPChassis:
    relationships:
      DEFAULTS:
        grid_display: false
        details_display: false
      hpsystemboard: { grid_display: true}

In this example we are not displaying any relationship info in the grid or details panel.  Effectively reversing the default behavior.  Then on the hpsystemboard relationship we are turning on the grid display count.  notice I overrode the relationship name by specifying (hpsystemboard) in the relationships section.  

Using the relationship controls and property controls you can fully define what is rendered in the top level grid and the bottom details section.
